#
# Script module for module 'PartnerCenter' that is executed when 'PartnerCenter' is imported in a PowerShell session.
#
# Generated by: Microsoft Corporation
#
# Generated on: 02/12/2021
#

$PSDefaultParameterValues.Clear()
Set-StrictMode -Version Latest

function Test-DotNet
{
    try
    {
        if ((Get-PSDrive 'HKLM' -ErrorAction Ignore) -and (-not (Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\' -ErrorAction Stop | Get-ItemPropertyValue -ErrorAction Stop -Name Release | Where { $_ -ge 461808 })))
        {
            throw ".NET Framework versions lower than 4.7.2 are not supported by the Partner Center module. Please upgrade to .NET Framework 4.7.2 or higher."
        }
    }
    catch [System.Management.Automation.DriveNotFoundException]
    {
        Write-Verbose ".NET Framework version check failed."
    }
}

if ($true -and ($PSEdition -eq 'Desktop'))
{
    if ($PSVersionTable.PSVersion -lt [Version]'5.1')
    {
        throw "PowerShell versions lower than 5.1 are not supported by the Partner Center module. Please upgrade to PowerShell 5.1 or higher."
    }

    Test-DotNet
}

if (Test-Path -Path "$PSScriptRoot\StartupScripts" -ErrorAction Ignore)
{
    Get-ChildItem "$PSScriptRoot\StartupScripts" -ErrorAction Stop | ForEach-Object {
        . $_.FullName
    }
}

$preloadPath = (Join-Path $PSScriptRoot -ChildPath "PreloadAssemblies")
if($PSEdition -eq 'Desktop' -and (Test-Path $preloadPath -ErrorAction Ignore))
{
    try
    {
        Get-ChildItem -ErrorAction Stop -Path $preloadPath -Filter "*.dll" | ForEach-Object {
            Add-Type -Path $_.FullName -ErrorAction Ignore | Out-Null
        }
    }
    catch {}
}

$dependencyPath = (Join-Path $PSScriptRoot -ChildPath "Dependencies")
if($PSEdition -eq 'Desktop' -and (Test-Path $dependencyPath -ErrorAction Ignore))
{
    try
    {
        Get-ChildItem -ErrorAction Stop -Path $dependencyPath -Filter "*.dll" | ForEach-Object {
            [System.Reflection.Assembly]::LoadFrom($_.FullName) | Out-Null
        }
    }
    catch {}
}

# PowerShell Core / PS7+: isolate dependencies to avoid collisions with
# other modules (for example Az.*) that load different versions of the same DLLs.
if ($PSEdition -eq 'Core')
{
    $script:dependencyDir = Join-Path $PSScriptRoot 'Dependencies'

    if (Test-Path $script:dependencyDir)
    {
        try
        {
            Add-Type -TypeDefinition @"
using System;
using System.IO;
using System.Reflection;
using System.Runtime.Loader;

namespace Microsoft.Store.PartnerCenter.PowerShell
{
    public static class DependencyResolver
    {
        private static readonly AssemblyLoadContext s_alc =
            new AssemblyLoadContext("PartnerCenter", false);
        private static string s_dependencyDir;

        public static void Initialize(string dependencyDir)
        {
            s_dependencyDir = dependencyDir;
            AssemblyLoadContext.Default.Resolving += Resolve;
        }

        public static void Cleanup()
        {
            AssemblyLoadContext.Default.Resolving -= Resolve;
        }

        private static Assembly Resolve(AssemblyLoadContext context, AssemblyName name)
        {
            string path = Path.Combine(s_dependencyDir, name.Name + ".dll");

            if (File.Exists(path))
            {
                return s_alc.LoadFromAssemblyPath(path);
            }

            return null;
        }
    }
}
"@
            [Microsoft.Store.PartnerCenter.PowerShell.DependencyResolver]::Initialize($script:dependencyDir)
        }
        catch
        {
            Write-Verbose "Failed to initialize ALC dependency resolver: $_"
        }
    }
}

Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Store.PartnerCenter.PowerShell.dll)

if (Test-Path -Path "$PSScriptRoot\PostImportScripts" -ErrorAction Ignore)
{
    Get-ChildItem "$PSScriptRoot\PostImportScripts" -ErrorAction Stop | ForEach-Object {
        . $_.FullName
    }
}
